version: "3.2"

services:

  functions-node-18:
    image: functions-node-18
    build:
      context: ..
      dockerfile: ./docker/functions-node-18/Dockerfile
    command: /bin/true

  cosmosdb:
    image: cosmosdb
    env_file:
      - ./environments/generated/env.cosmosdb
    build:
      context: ../docker/cosmosdb
      dockerfile: ./Dockerfile
    ports:
      - ${COSMOSDB_PORT}:3000

  cosmosdbrc:
    image: cosmosdb
    container_name: cosmosdbrc
    env_file:
      - ./environments/generated/env.rc.cosmosdb
    build:
      context: ../docker/cosmosdb
      dockerfile: ./Dockerfile
    ports:
      - 3001:${RC_COSMOSDB_PORT}

  redis:
    container_name: redis
    image: wodby/redis:3.2-2.1.5@sha256:09a82ade1f06069201c4d055e7ed759702880e34653222ae677375019e6ebd41
    ports:
        - "6379:6379"
    environment:
        REDIS_TIMEOUT: 300
        REDIS_TCP_KEEPALIVE: 60
        REDIS_MAXMEMORY: 182m

  storage-account:
    image: azurite
    build:
      context: ../docker/azurite
      dockerfile: ./Dockerfile
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

  function:
    image: fn
    env_file:
      - ./environments/generated/env.function
    build:
      context: ..
      dockerfile: ./docker/functions/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7071/api/v1/ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - ${FUNCTION_PORT}:7071
    links:
      - cosmosdb
      - cosmosdbrc
      - redis
      - storage-account
    depends_on:
      - functions-node-18

  testagent:
    image: node:16-alpine@sha256:a1f9d027912b58a7c75be7716c97cfbc6d3099f3a97ed84aa490be9dee20e787
    working_dir: /usr/src/app
    command: tail -f /dev/null # to keep it   up&running
    env_file:
      - environments/generated/env.integration-tests
    volumes:
      - "./:/usr/src/app"
      - "../openapi:/usr/src/openapi"
    depends_on:
      function:
        condition: service_healthy
      cosmosdb:
        condition: service_started
      cosmosdbrc:
        condition: service_started
      storage-account:
        condition: service_started
    links:
      - function
